// All static game data for Albion Online Oracle.
// Loaded before data.js. Exposes window._aooStatic consumed by data.js.
window._aooStatic = {

  /* ---------- Cities ---------- */
  CITIES: [
    { id: 'bridgewatch', name: 'Bridgewatch', biome: 'desert', tint: '#c97a2a',
      bonuses: { plate: 0.36, plate_weapon: 0.36, stoneblock: 0.36 },
      desc: { fr: 'Cité du désert. Spécialiste des armures de plates et des armes de mêlée en métal.', en: 'Desert city. Plate armour and metal melee weapons specialist.' } },
    { id: 'lymhurst', name: 'Lymhurst', biome: 'forest', tint: '#5a8a3a',
      bonuses: { leather: 0.36, planks: 0.36, hunter_weapon: 0.20 },
      desc: { fr: 'Cité de la forêt. Spécialiste du cuir et des planches, légère bonification sur les armes de chasseur.', en: 'Forest city. Leather and planks specialist, slight bonus on hunter weapons.' } },
    { id: 'martlock', name: 'Martlock', biome: 'highlands', tint: '#4a6c8a',
      bonuses: { offhand: 0.36, hide: 0.36 },
      desc: { fr: 'Cité des Highlands. Spécialiste des objets de main secondaire et du tannage.', en: 'Highlands city. Off-hands and tanning specialist.' } },
    { id: 'fortsterling', name: 'Fort Sterling', biome: 'steppe', tint: '#b8b3a0',
      bonuses: { cloth_armor: 0.36, planks: 0.20 },
      desc: { fr: 'Cité des steppes. Spécialiste des armures en tissu.', en: 'Steppe city. Cloth armour specialist.' } },
    { id: 'thetford', name: 'Thetford', biome: 'swamp', tint: '#7d5aa8',
      bonuses: { magic_weapon: 0.36, cloth: 0.36 },
      desc: { fr: 'Cité des marais. Spécialiste des armes magiques et du tissage.', en: 'Swamp city. Magic weapons and cloth specialist.' } },
    { id: 'caerleon', name: 'Caerleon', biome: 'royal', tint: '#a83232',
      bonuses: { all: 0.117 },
      desc: { fr: 'Cité royale au cœur des terres noires. Petit bonus universel, fort volume de marché.', en: 'Royal city at the heart of the black zones. Small universal bonus, high market volume.' } },
    { id: 'brecilien', name: 'Brecilien', biome: 'mist', tint: '#3aa8a0',
      bonuses: { all: 0.25 },
      desc: { fr: 'Cité cachée des Brumes. Bonus universel le plus élevé, mais marché plus discret.', en: 'Hidden city in the Mists. Highest universal bonus, but a quieter market.' } },
  ],

  /* ---------- Resources ---------- */
  RESOURCES: {
    planks:   { name: { fr: 'Planches', en: 'Planks' },     family: 'planks',
      tiers: { 2: { fr:'Planches de Bouleau', en:'Birch Planks'},
               3: { fr:'Planches de Châtaignier', en:'Chestnut Planks'},
               4: { fr:'Planches de Pin', en:'Pine Planks'},
               5: { fr:'Planches de Cèdre', en:'Cedar Planks'},
               6: { fr:'Planches de Chêne', en:'Bloodoak Planks'},
               7: { fr:'Planches d\'Écorcecendre', en:'Ashenbark Planks'},
               8: { fr:'Planches de Bois Blanc', en:'Whitewood Planks'} } },
    metalbar: { name: { fr: 'Lingots', en: 'Metal bars' },  family: 'metal',
      tiers: { 2: { fr:'Lingots d\'Étain', en:'Tin Bar'},
               3: { fr:'Lingots de Cuivre', en:'Bronze Bar'},
               4: { fr:'Lingots d\'Acier', en:'Steel Bar'},
               5: { fr:'Lingots de Titane', en:'Titanium Steel Bar'},
               6: { fr:'Lingots de Runite', en:'Runite Steel Bar'},
               7: { fr:'Lingots de Météorite', en:'Meteorite Steel Bar'},
               8: { fr:'Lingots d\'Adamantium', en:'Adamantium Steel Bar'} } },
    leather:  { name: { fr: 'Cuir', en: 'Leather' },        family: 'leather',
      tiers: { 2: { fr:'Cuir Brut', en:'Stiff Leather'},
               3: { fr:'Cuir Fin', en:'Thin Leather'},
               4: { fr:'Cuir Moyen', en:'Medium Leather'},
               5: { fr:'Cuir Lourd', en:'Heavy Leather'},
               6: { fr:'Cuir Robuste', en:'Robust Leather'},
               7: { fr:'Cuir Épais', en:'Thick Leather'},
               8: { fr:'Cuir Résilient', en:'Resilient Leather'} } },
    cloth:    { name: { fr: 'Tissu', en: 'Cloth' },         family: 'cloth',
      tiers: { 2: { fr:'Toile Simple', en:'Simple Cloth'},
               3: { fr:'Soie Légère', en:'Neat Cloth'},
               4: { fr:'Soie Tissée', en:'Fine Cloth'},
               5: { fr:'Soie d\'Araignée', en:'Ornate Cloth'},
               6: { fr:'Soie Sombre', en:'Lavish Cloth'},
               7: { fr:'Soie Royale', en:'Opulent Cloth'},
               8: { fr:'Soie Asmodéenne', en:'Baroque Cloth'} } },
    herb:     { name: { fr: 'Herbes', en: 'Herbs' },        family: 'herb',
      tiers: { 2: { fr:'Agaric ésotérique',       en:'Arcane Agaric'},
               3: { fr:'Consoude feuille-vive',    en:'Brightleaf Comfrey'},
               4: { fr:'Chardon crénelé',          en:'Crenellated Burdock'},
               5: { fr:'Cardère incendiaire',      en:'Dragon Teasel'},
               6: { fr:'Digitale furtive',         en:'Elusive Foxglove'},
               7: { fr:'Molène ardente',           en:'Firetouched Mullein'},
               8: { fr:'Mille-feuille morbide',    en:'Ghoul Yarrow'} } },
    farm:     { name: { fr: 'Produits agricoles', en: 'Farm products' }, family: 'farm',
      tiers: { 2: { fr:'Maïs', en:'Corn'},
               3: { fr:'Blé', en:'Wheat'},
               4: { fr:'Citrouille', en:'Pumpkin'},
               5: { fr:'Chou', en:'Cabbage'},
               6: { fr:'Pomme de terre', en:'Potato'},
               7: { fr:'Navet', en:'Turnip'},
               8: { fr:'Carotte', en:'Carrot'} } },
  },

  /* ---------- Tier names & multipliers ---------- */
  TIER_NAME: {
    fr: { 2:'du novice', 3:'du compagnon', 4:"de l'adepte", 5:"de l'expert", 6:'du maître', 7:'du grand maître', 8:'du sage' },
    en: { 2:"Novice's", 3:"Journeyman's", 4:"Adept's", 5:"Expert's", 6:"Master's", 7:"Grandmaster's", 8:"Elder's" },
  },
  ENCH_MULT:    { 0: 1, 1: 3.6, 2: 9.5, 3: 24, 4: 60 },
  QUALITY_MULT: { 1: 1.0, 2: 1.2, 3: 1.5, 4: 2.0, 5: 3.0 },
  QUALITY_LABEL: {
    fr: { 1: 'Normal', 2: 'Bon', 3: 'Remarquable', 4: 'Excellent', 5: 'Chef-d\'œuvre' },
    en: { 1: 'Normal', 2: 'Good', 3: 'Outstanding', 4: 'Excellent', 5: 'Masterpiece' },
  },

  /* ---------- Recipes ---------- */
  // Quantities at item-tier T. Simplified — real Albion has small per-item variations.
  RECIPES: {
    bow_2h:           (T) => [ {res:'planks',   tier:T, qty:16}, {res:'planks',   tier:Math.max(2,T-1), qty:8} ],
    bow_1h:           (T) => [ {res:'planks',   tier:T, qty:8},  {res:'planks',   tier:Math.max(2,T-1), qty:4} ],
    sword_1h:         (T) => [ {res:'metalbar', tier:T, qty:8} ],
    sword_2h:         (T) => [ {res:'metalbar', tier:T, qty:16}, {res:'metalbar', tier:Math.max(2,T-1), qty:8} ],
    dagger_1h:        (T) => [ {res:'metalbar', tier:T, qty:6},  {res:'leather',  tier:Math.max(2,T-1), qty:4} ],
    spear_2h:         (T) => [ {res:'metalbar', tier:T, qty:12}, {res:'planks',   tier:T, qty:8} ],
    staff_2h_metal:   (T) => [ {res:'metalbar', tier:T, qty:12}, {res:'cloth',    tier:T, qty:8} ],
    staff_2h_wood:    (T) => [ {res:'planks',   tier:T, qty:12}, {res:'cloth',    tier:T, qty:8} ],
    staff_1h_wood:    (T) => [ {res:'planks',   tier:T, qty:6},  {res:'cloth',    tier:Math.max(2,T-1), qty:4} ],
    plate_helm:       (T) => [ {res:'metalbar', tier:T, qty:6},  {res:'leather',  tier:Math.max(2,T-1), qty:2} ],
    plate_armor:      (T) => [ {res:'metalbar', tier:T, qty:12}, {res:'leather',  tier:Math.max(2,T-1), qty:4} ],
    plate_boots:      (T) => [ {res:'metalbar', tier:T, qty:6},  {res:'leather',  tier:Math.max(2,T-1), qty:2} ],
    leather_helm:     (T) => [ {res:'leather',  tier:T, qty:6},  {res:'cloth',    tier:Math.max(2,T-1), qty:2} ],
    leather_armor:    (T) => [ {res:'leather',  tier:T, qty:12}, {res:'cloth',    tier:Math.max(2,T-1), qty:4} ],
    leather_boots:    (T) => [ {res:'leather',  tier:T, qty:6},  {res:'cloth',    tier:Math.max(2,T-1), qty:2} ],
    cloth_helm:       (T) => [ {res:'cloth',    tier:T, qty:6},  {res:'leather',  tier:Math.max(2,T-1), qty:2} ],
    cloth_armor:      (T) => [ {res:'cloth',    tier:T, qty:12}, {res:'leather',  tier:Math.max(2,T-1), qty:4} ],
    cloth_boots:      (T) => [ {res:'cloth',    tier:T, qty:6},  {res:'leather',  tier:Math.max(2,T-1), qty:2} ],
    shield:           (T) => [ {res:'metalbar', tier:T, qty:8},  {res:'planks',   tier:Math.max(2,T-1), qty:8} ],
    tower_shield:     (T) => [ {res:'metalbar', tier:T, qty:12}, {res:'planks',   tier:Math.max(2,T-1), qty:8} ],
    torch:            (T) => [ {res:'planks',   tier:T, qty:6},  {res:'cloth',    tier:Math.max(2,T-1), qty:2} ],
    book:             (T) => [ {res:'cloth',    tier:T, qty:8},  {res:'leather',  tier:Math.max(2,T-1), qty:4} ],
    cape:             (T) => [ {res:'cloth',    tier:T, qty:8},  {res:'leather',  tier:Math.max(2,T-1), qty:8} ],
    dagger_2h:        (T) => [ {res:'metalbar', tier:T, qty:12}, {res:'leather',  tier:T, qty:8} ],
    quarterstaff_1h:  (T) => [ {res:'planks',   tier:T, qty:8} ],
    quarterstaff_2h:  (T) => [ {res:'planks',   tier:T, qty:16}, {res:'metalbar', tier:Math.max(2,T-1), qty:8} ],
    knuckles_1h:      (T) => [ {res:'metalbar', tier:T, qty:6},  {res:'leather',  tier:Math.max(2,T-1), qty:4} ],
    knuckles_2h:      (T) => [ {res:'metalbar', tier:T, qty:12}, {res:'leather',  tier:T, qty:8} ],
    orb:              (T) => [ {res:'cloth',    tier:T, qty:8},  {res:'leather',  tier:Math.max(2,T-1), qty:2} ],
    totem:            (T) => [ {res:'planks',   tier:T, qty:6},  {res:'cloth',    tier:Math.max(2,T-1), qty:2} ],
    horn:             (T) => [ {res:'leather',  tier:T, qty:8},  {res:'cloth',    tier:Math.max(2,T-1), qty:4} ],
    bag:              (T) => [ {res:'cloth',    tier:T, qty:8},  {res:'leather',  tier:Math.max(2,T-1), qty:4} ],
    potion:           (T) => [ {res:'herb',     tier:T, qty:8} ],
    food_simple:      (T) => [ {res:'farm',     tier:T, qty:8} ],
    food_complex:     (T) => [ {res:'farm',     tier:T, qty:12}, {res:'farm',     tier:Math.max(2,T-1), qty:4} ],
    food_meat:        (T) => [ {res:'farm',     tier:T, qty:8},  {res:'herb',     tier:Math.max(2,T-1), qty:2} ],
    tool_metal:       (T) => [ {res:'metalbar', tier:T, qty:12}, {res:'planks',   tier:T, qty:8} ],
    tool_wood:        (T) => [ {res:'planks',   tier:T, qty:12}, {res:'metalbar', tier:Math.max(2,T-1), qty:4} ],
  },

  /* ---------- Item archetypes ---------- */
  // category drives city-bonus matching:
  //   plate / plate_weapon → Bridgewatch  |  leather / hunter_weapon → Lymhurst
  //   cloth_armor → Fort Sterling         |  magic_weapon → Thetford
  //   offhand → Martlock                  |  tool / bag / cape → no bonus
  ITEMS: [

    // ══════════════════════════════════════════════════════════════
    // GUERRIER — Armure de plaques
    // ══════════════════════════════════════════════════════════════

    // ── Épées ──
    { id:'MAIN_SWORD',               name:{ fr:'Épée large',                    en:'Broadsword' },              group:'weapon_sword',        category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },
    { id:'2H_CLAYMORE',              name:{ fr:'Claymore',                       en:'Claymore' },                group:'weapon_sword',        category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_DUALSWORD',             name:{ fr:'Épée double',                    en:'Dual Swords' },             group:'weapon_sword',        category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_CLAYMORE_AVALON',       name:{ fr:'Adoube-roi',                     en:'Kingmaker' },               group:'weapon_sword',        category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'MAIN_SCIMITAR_MORGANA',    name:{ fr:'Lame de Clarent',                en:'Clarent Blade' },           group:'weapon_sword',        category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },
    { id:'2H_CLEAVER_HELL',          name:{ fr:'Épée tranchante',                en:'Carving Sword' },           group:'weapon_sword',        category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_DUALSCIMITAR_UNDEAD',   name:{ fr:'Paire de galatines',             en:'Galatine Pair' },           group:'weapon_sword',        category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'MAIN_SWORD_CRYSTAL',       name:{ fr:'Lame infinie',                   en:'Infinity Blade' },          group:'weapon_sword',        category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },

    // ── Haches ──
    { id:'MAIN_AXE',                 name:{ fr:'Hache de guerre',                en:'Battleaxe' },               group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },
    { id:'2H_AXE',                   name:{ fr:'Grande hache',                   en:'Greataxe' },                group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_HALBERD',               name:{ fr:'Hallebarde',                     en:'Halberd' },                 group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_SCYTHE_HELL',           name:{ fr:'Faux infernale',                 en:'Infernal Scythe' },         group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_AXE_AVALON',            name:{ fr:'Brise-royaume',                  en:'Realmbreaker' },            group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_HALBERD_MORGANA',       name:{ fr:'Mande-charogne',                 en:'Carrioncaller' },           group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_DUALAXE_KEEPER',        name:{ fr:"Pattes d'ours",                  en:'Bear Paws' },               group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_SCYTHE_CRYSTAL',        name:{ fr:'Faucheuse de cristal',           en:'Crystal Reaper' },          group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_TWINSCYTHE_HELL',       name:{ fr:'Fauchâme',                       en:'Soulscythe' },              group:'weapon_axe',          category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },

    // ── Masses & Marteaux ──
    { id:'MAIN_MACE',                name:{ fr:'Masse',                          en:'Mace' },                    group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },
    { id:'MAIN_HAMMER',              name:{ fr:'Marteau',                        en:'Hammer' },                  group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },
    { id:'2H_HAMMER',                name:{ fr:'Grand marteau',                  en:'Great Hammer' },            group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_FLAIL',                 name:{ fr:'Morgenstern',                    en:'Morning Star' },            group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_POLEHAMMER',            name:{ fr:'Bec de corbin',                  en:'Polehammer' },              group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_HAMMER_AVALON',         name:{ fr:'Main de justice',                en:'Hand of Justice' },         group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_HAMMER_UNDEAD',         name:{ fr:'Martel-tombe',                   en:'Tombhammer' },              group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'MAIN_MACE_HELL',           name:{ fr:"Masse d'incube",                 en:'Incubus Mace' },            group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },
    { id:'2H_DUALHAMMER_HELL',       name:{ fr:'Marteaux forgés',                en:'Forge Hammers' },           group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_RAM_KEEPER',            name:{ fr:'Gardien du bosquet',             en:'Grovekeeper' },             group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_HAMMER_CRYSTAL',        name:{ fr:'Marteau de Foudre',              en:'Truebolt Hammer' },         group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_MACE',                  name:{ fr:'Masse lourde',                   en:'Heavy Mace' },              group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'MAIN_ROCKMACE_KEEPER',     name:{ fr:'Masse du soubassement',          en:'Bedrock Mace' },            group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },
    { id:'2H_MACE_MORGANA',          name:{ fr:'Masse de Camlann',               en:'Camlann Mace' },            group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'2H_DUALMACE_AVALON',       name:{ fr:'Gardes-serment',                 en:'Oathkeepers' },             group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_2h' },
    { id:'MAIN_MACE_CRYSTAL',        name:{ fr:'Monarque des tempêtes',          en:'Dreadstorm Monarch' },      group:'weapon_hammer',       category:'plate_weapon',   iconGlyph:'sword',    recipeKey:'sword_1h' },

    // ── Armure de plaques ──
    { id:'HEAD_PLATE_SET1',          name:{ fr:'Casque de soldat',               en:'Soldier Helmet' },          group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_SET1',         name:{ fr:'Armure de soldat',               en:'Soldier Armor' },           group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_SET1',         name:{ fr:'Bottes de soldat',               en:'Soldier Boots' },           group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },
    { id:'HEAD_PLATE_SET2',          name:{ fr:'Casque de chevalier',            en:'Knight Helmet' },           group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_SET2',         name:{ fr:'Armure de chevalier',            en:'Knight Armor' },            group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_SET2',         name:{ fr:'Bottes de chevalier',            en:'Knight Boots' },            group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },
    { id:'HEAD_PLATE_SET3',          name:{ fr:'Casque de gardien',              en:'Guardian Helmet' },         group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_SET3',         name:{ fr:'Armure de gardien',              en:'Guardian Armor' },          group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_SET3',         name:{ fr:'Bottes de gardien',              en:'Guardian Boots' },          group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },
    { id:'HEAD_PLATE_UNDEAD',        name:{ fr:'Casque de gardetombe',           en:'Graveguard Helmet' },       group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_UNDEAD',       name:{ fr:'Armure de gardetombe',           en:'Graveguard Armor' },        group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_UNDEAD',       name:{ fr:'Bottes de gardetombe',           en:'Graveguard Boots' },        group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },
    { id:'HEAD_PLATE_KEEPER',        name:{ fr:'Casque de judicateur',           en:'Judicator Helmet' },        group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_KEEPER',       name:{ fr:'Armure de judicateur',           en:'Judicator Armor' },         group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_KEEPER',       name:{ fr:'Bottes de judicateur',           en:'Judicator Boots' },         group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },
    { id:'HEAD_PLATE_HELL',          name:{ fr:'Casque de démon',                en:'Demon Helmet' },            group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_HELL',         name:{ fr:'Armure de démon',                en:'Demon Armor' },             group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_HELL',         name:{ fr:'Bottes de démon',                en:'Demon Boots' },             group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },
    { id:'HEAD_PLATE_FEY',           name:{ fr:'Casque crépusculaire',           en:'Duskweaver Helmet' },       group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_FEY',          name:{ fr:'Armure crépusculaire',           en:'Duskweaver Armor' },        group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_FEY',          name:{ fr:'Bottes crépusculaires',          en:'Duskweaver Boots' },        group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },
    { id:'HEAD_PLATE_AVALON',        name:{ fr:'Casque de bravoure',             en:'Helmet of Valor' },         group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_AVALON',       name:{ fr:'Armure de bravoure',             en:'Armor of Valor' },          group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_AVALON',       name:{ fr:'Bottes de bravoure',             en:'Boots of Valor' },          group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },
    { id:'HEAD_PLATE_ROYAL',         name:{ fr:'Casque royal',                   en:'Royal Helmet' },            group:'armor_plate',         category:'plate',           iconGlyph:'helm',     recipeKey:'plate_helm' },
    { id:'ARMOR_PLATE_ROYAL',        name:{ fr:'Armure royale',                  en:'Royal Armor' },             group:'armor_plate',         category:'plate',           iconGlyph:'plate',    recipeKey:'plate_armor' },
    { id:'SHOES_PLATE_ROYAL',        name:{ fr:'Bottes royales',                 en:'Royal Boots' },             group:'armor_plate',         category:'plate',           iconGlyph:'boots',    recipeKey:'plate_boots' },

    // ══════════════════════════════════════════════════════════════
    // CHASSEUR — Armure de cuir
    // ══════════════════════════════════════════════════════════════

    // ── Arcs & Arbalètes ──
    { id:'2H_BOW',                   name:{ fr:'Arc',                            en:'Bow' },                     group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_LONGBOW',               name:{ fr:'Arc long',                       en:'Longbow' },                 group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_CROSSBOW',              name:{ fr:'Arbalète',                       en:'Crossbow' },                group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_CROSSBOWLARGE',         name:{ fr:'Arbalète lourde',                en:'Heavy Crossbow' },          group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'MAIN_1HCROSSBOW',          name:{ fr:'Arbalète légère',                en:'Light Crossbow' },          group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_1h' },
    { id:'2H_WARBOW',                name:{ fr:'Arc de guerre',                  en:'Warbow' },                  group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_BOW_KEEPER',            name:{ fr:'Arc de Badon',                   en:'Bow of Badon' },            group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_BOW_AVALON',            name:{ fr:'Perce-brume',                    en:'Mistpiercer' },             group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_BOW_HELL',              name:{ fr:'Arc gémissant',                  en:'Wailing Bow' },             group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_LONGBOW_UNDEAD',        name:{ fr:'Arc murmurant',                  en:'Whispering Bow' },          group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_CROSSBOWLARGE_MORGANA', name:{ fr:'Arc de siège',                   en:'Siegebow' },                group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_BOW_CRYSTAL',           name:{ fr:'Arc Marche-ciel',                en:'Skystrider Bow' },          group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_REPEATINGCROSSBOW_UNDEAD', name:{ fr:'Arbalète à répétition des larmes', en:'Weeping Repeater' }, group:'weapon_bow',           category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_DUALCROSSBOW_HELL',     name:{ fr:'Lanceurs de foudre',             en:'Boltcasters' },             group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_CROSSBOW_CANNON_AVALON',name:{ fr:"Matrice d'énergie",              en:'Energy Shaper' },           group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },
    { id:'2H_DUALCROSSBOW_CRYSTAL',  name:{ fr:'Désintégrateurs de Lumière',     en:'Arclight Blasters' },       group:'weapon_bow',          category:'hunter_weapon',  iconGlyph:'bow',      recipeKey:'bow_2h' },

    // ── Lances ──
    { id:'MAIN_SPEAR',               name:{ fr:'Lance',                          en:'Spear' },                   group:'weapon_spear',        category:'hunter_weapon',  iconGlyph:'spear',    recipeKey:'sword_1h' },
    { id:'2H_SPEAR',                 name:{ fr:'Pique',                          en:'Pike' },                    group:'weapon_spear',        category:'hunter_weapon',  iconGlyph:'spear',    recipeKey:'spear_2h' },
    { id:'2H_GLAIVE',                name:{ fr:'Glaive',                         en:'Glaive' },                  group:'weapon_spear',        category:'hunter_weapon',  iconGlyph:'spear',    recipeKey:'spear_2h' },
    { id:'MAIN_SPEAR_KEEPER',        name:{ fr:'Lance de héron',                 en:'Heron Spear' },             group:'weapon_spear',        category:'hunter_weapon',  iconGlyph:'spear',    recipeKey:'sword_1h' },
    { id:'2H_HARPOON_HELL',          name:{ fr:'Chassesprit',                    en:'Spirithunter' },            group:'weapon_spear',        category:'hunter_weapon',  iconGlyph:'spear',    recipeKey:'spear_2h' },
    { id:'2H_TRIDENT_UNDEAD',        name:{ fr:'Lance de la trinité',            en:'Trinity Spear' },           group:'weapon_spear',        category:'hunter_weapon',  iconGlyph:'spear',    recipeKey:'spear_2h' },
    { id:'MAIN_SPEAR_LANCE_AVALON',  name:{ fr:'Diurnebris',                     en:'Daybreaker' },              group:'weapon_spear',        category:'hunter_weapon',  iconGlyph:'spear',    recipeKey:'sword_1h' },
    { id:'2H_GLAIVE_CRYSTAL',        name:{ fr:'Glaive déchirant',               en:'Rift Glaive' },             group:'weapon_spear',        category:'hunter_weapon',  iconGlyph:'spear',    recipeKey:'spear_2h' },

    // ── Bâtons de combat ──
    { id:'2H_QUARTERSTAFF',          name:{ fr:'Bâton double',                   en:'Quarterstaff' },            group:'weapon_quarterstaff', category:'hunter_weapon',  iconGlyph:'staff',    recipeKey:'quarterstaff_2h' },
    { id:'2H_DOUBLEBLADEDSTAFF',     name:{ fr:'Bâton à double tranchant',       en:'Double Bladed Staff' },     group:'weapon_quarterstaff', category:'hunter_weapon',  iconGlyph:'staff',    recipeKey:'staff_2h_wood' },
    { id:'2H_QUARTERSTAFF_AVALON',   name:{ fr:'Cherchegraal',                   en:'Grailseeker' },             group:'weapon_quarterstaff', category:'hunter_weapon',  iconGlyph:'staff',    recipeKey:'quarterstaff_2h' },
    { id:'2H_IRONCLADEDSTAFF',       name:{ fr:'Bâton sans faille',              en:'Iron-clad Staff' },         group:'weapon_quarterstaff', category:'hunter_weapon',  iconGlyph:'staff',    recipeKey:'quarterstaff_2h' },
    { id:'2H_COMBATSTAFF_MORGANA',   name:{ fr:'Bâton de moine noir',            en:'Black Monk Stave' },        group:'weapon_quarterstaff', category:'hunter_weapon',  iconGlyph:'staff',    recipeKey:'quarterstaff_2h' },
    { id:'2H_ROCKSTAFF_KEEPER',      name:{ fr:"Bâton d'équilibre",              en:'Staff of Balance' },        group:'weapon_quarterstaff', category:'hunter_weapon',  iconGlyph:'staff',    recipeKey:'quarterstaff_2h' },
    { id:'2H_DOUBLEBLADEDSTAFF_CRYSTAL', name:{ fr:'Lame double fantôme',        en:'Phantom Twinblade' },       group:'weapon_quarterstaff', category:'hunter_weapon',  iconGlyph:'staff',    recipeKey:'staff_2h_wood' },

    // ── Armure de cuir ──
    { id:'HEAD_LEATHER_SET1',        name:{fr:'Capuche de mercenaire',           en:'Mercenary Hood' },          group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_SET1',       name:{fr:'Veste de mercenaire',             en:'Mercenary Jacket' },        group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_SET1',       name:{fr:'Chaussures de mercenaire',        en:'Mercenary Shoes' },         group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },
    { id:'HEAD_LEATHER_SET2',        name:{fr:'Capuche de chasseur',             en:'Hunter Hood' },             group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_SET2',       name:{fr:'Veste de chasseur',               en:'Hunter Jacket' },           group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_SET2',       name:{fr:'Chaussures de chasseur',          en:'Hunter Shoes' },            group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },
    { id:'HEAD_LEATHER_SET3',        name:{fr:"Capuche d'assassin",              en:'Assassin Hood' },           group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_SET3',       name:{fr:"Veste d'assassin",                en:'Assassin Jacket' },         group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_SET3',       name:{fr:"Chaussures d'assassin",           en:'Assassin Shoes' },          group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },
    { id:'HEAD_LEATHER_UNDEAD',      name:{ fr:'Capuche de spectre',             en:'Specter Hood' },            group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_UNDEAD',     name:{ fr:'Veste de spectre',               en:'Specter Jacket' },          group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_UNDEAD',     name:{ fr:'Chaussures de spectre',          en:'Specter Shoes' },           group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },
    { id:'HEAD_LEATHER_MORGANA',     name:{ fr:'Capuche de traqueur',            en:'Stalker Hood' },            group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_MORGANA',    name:{ fr:'Veste de traqueur',              en:'Stalker Jacket' },          group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_MORGANA',    name:{ fr:'Chaussures de traqueur',         en:'Stalker Shoes' },           group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },
    { id:'HEAD_LEATHER_HELL',        name:{ fr:'Capuche de tourmenteur',         en:'Hellion Hood' },            group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_HELL',       name:{ fr:'Veste de tourmenteur',           en:'Hellion Jacket' },          group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_HELL',       name:{ fr:'Chaussures de tourmenteur',      en:'Hellion Shoes' },           group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },
    { id:'HEAD_LEATHER_FEY',         name:{ fr:'Capuche de marcheur des brumes', en:'Mistwalker Hood' },         group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_FEY',        name:{ fr:'Veste de marcheur des brumes',   en:'Mistwalker Jacket' },       group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_FEY',        name:{ fr:'Chaussures de marcheur des brumes', en:'Mistwalker Shoes' },     group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },
    { id:'HEAD_LEATHER_AVALON',      name:{ fr:'Capuche de ténacité',            en:'Hood of Tenacity' },        group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_AVALON',     name:{ fr:'Veste de ténacité',              en:'Jacket of Tenacity' },      group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_AVALON',     name:{ fr:'Chaussures de ténacité',         en:'Shoes of Tenacity' },       group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },
    { id:'HEAD_LEATHER_ROYAL',       name:{ fr:'Capuche royale',                 en:'Royal Hood' },              group:'armor_leather',       category:'leather',         iconGlyph:'hood',     recipeKey:'leather_helm' },
    { id:'ARMOR_LEATHER_ROYAL',      name:{ fr:'Veste royale',                   en:'Royal Jacket' },            group:'armor_leather',       category:'leather',         iconGlyph:'jacket',   recipeKey:'leather_armor' },
    { id:'SHOES_LEATHER_ROYAL',      name:{ fr:'Chaussures royales',             en:'Royal Shoes' },             group:'armor_leather',       category:'leather',         iconGlyph:'boots',    recipeKey:'leather_boots' },

    // ══════════════════════════════════════════════════════════════
    // ASSASSIN — Armure de cuir
    // ══════════════════════════════════════════════════════════════

    // ── Dagues ──
    { id:'MAIN_DAGGER',              name:{ fr:'Dague',                          en:'Dagger' },                  group:'weapon_dagger',       category:'hunter_weapon',  iconGlyph:'sword',       recipeKey:'dagger_1h' },
    { id:'2H_DAGGERPAIR',            name:{ fr:'Paire de dagues',                en:'Dagger Pair' },             group:'weapon_dagger',       category:'hunter_weapon',  iconGlyph:'dagger_pair', recipeKey:'dagger_2h' },
    { id:'2H_CLAWPAIR',              name:{ fr:'Griffes',                        en:'Claws' },                   group:'weapon_dagger',       category:'hunter_weapon',  iconGlyph:'dagger_pair', recipeKey:'dagger_2h' },
    { id:'MAIN_DAGGER_HELL',         name:{ fr:'Croc-de-démon',                  en:'Demonfang' },               group:'weapon_dagger',       category:'hunter_weapon',  iconGlyph:'sword',       recipeKey:'dagger_1h' },
    { id:'MAIN_RAPIER_MORGANA',      name:{ fr:'Saigneur',                       en:'Bloodletter' },             group:'weapon_dagger',       category:'hunter_weapon',  iconGlyph:'sword',       recipeKey:'dagger_1h' },
    { id:'2H_DUALSICKLE_UNDEAD',     name:{ fr:'Sacrificateur',                  en:'Deathgivers' },             group:'weapon_dagger',       category:'hunter_weapon',  iconGlyph:'dagger_pair', recipeKey:'dagger_2h' },
    { id:'2H_DAGGER_KATAR_AVALON',   name:{ fr:'Brides-furie',                   en:'Bridled Fury' },            group:'weapon_dagger',       category:'hunter_weapon',  iconGlyph:'dagger_pair', recipeKey:'dagger_2h' },
    { id:'2H_DAGGERPAIR_CRYSTAL',    name:{ fr:'Jumelles tueuses',               en:'Twin Slayers' },            group:'weapon_dagger',       category:'hunter_weapon',  iconGlyph:'dagger_pair', recipeKey:'dagger_2h' },

    // ── Poings & Gantelets ──
    { id:'2H_KNUCKLES_SET1',         name:{ fr:'Gantelets de bagarreur',         en:'Brawler Gloves' },          group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },
    { id:'2H_KNUCKLES_SET2',         name:{ fr:'Brassards de bataille',          en:'Battle Bracers' },          group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },
    { id:'2H_KNUCKLES_SET3',         name:{ fr:'Gantelets à pointes',            en:'Spiked Gauntlets' },        group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },
    { id:'2H_KNUCKLES_AVALON',       name:{ fr:"Poings d'Avalon",                en:'Fists of Avalon' },         group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },
    { id:'2H_KNUCKLES_HELL',         name:{ fr:'Mains infernales',               en:'Hellfire Hands' },          group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },
    { id:'2H_KNUCKLES_KEEPER',       name:{ fr:'Poignes ursines',                en:'Ursine Maulers' },          group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },
    { id:'2H_KNUCKLES_MORGANA',      name:{ fr:'Cestes-des-freux',               en:'Ravenstrike Cestus' },      group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },
    { id:'2H_IRONGAUNTLETS_HELL',    name:{ fr:'Mains noires',                   en:'Black Hands' },             group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },
    { id:'2H_KNUCKLES_CRYSTAL',      name:{ fr:"Brassards d'Impulsion de Force", en:'Forcepulse Bracers' },      group:'weapon_knuckles',     category:'hunter_weapon',  iconGlyph:'knuckles',    recipeKey:'knuckles_2h' },

    // ══════════════════════════════════════════════════════════════
    // MAGE — Armure de tissu
    // ══════════════════════════════════════════════════════════════

    // ── Bâtons de feu ──
    { id:'MAIN_FIRESTAFF',           name:{ fr:'Bâton de feu',                   en:'Fire Staff' },              group:'weapon_staff_fire',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'2H_FIRESTAFF',             name:{ fr:'Grand bâton de feu',             en:'Great Fire Staff' },        group:'weapon_staff_fire',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_INFERNOSTAFF',          name:{ fr:'Bâton infernal',                 en:'Infernal Staff' },          group:'weapon_staff_fire',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_FIRESTAFF_HELL',        name:{ fr:'Bâton sulfureux',                en:'Brimstone Staff' },         group:'weapon_staff_fire',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_INFERNOSTAFF_MORGANA',  name:{ fr:'Bâton ardent',                   en:'Blazing Staff' },           group:'weapon_staff_fire',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_FIRE_RINGPAIR_AVALON',  name:{ fr:"Aria de l'aube",                 en:'Dawnsong' },                group:'weapon_staff_fire',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'MAIN_FIRESTAFF_KEEPER',    name:{ fr:'Bâton braisier',                 en:'Wildfire Staff' },          group:'weapon_staff_fire',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'MAIN_FIRESTAFF_CRYSTAL',   name:{ fr:'Bâton de Marcheflammes',         en:'Flamewalker Staff' },       group:'weapon_staff_fire',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },

    // ── Bâtons de givre ──
    { id:'MAIN_FROSTSTAFF',          name:{ fr:'Bâton de givre',                 en:'Frost Staff' },             group:'weapon_staff_frost',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'2H_FROSTSTAFF',            name:{ fr:'Grand bâton de givre',           en:'Great Frost Staff' },       group:'weapon_staff_frost',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_GLACIALSTAFF',          name:{ fr:'Bâton glacial',                  en:'Glacial Staff' },           group:'weapon_staff_frost',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_ICEGAUNTLETS_HELL',     name:{ fr:'Bâton de stalactite',            en:'Icicle Staff' },            group:'weapon_staff_frost',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_ICECRYSTAL_UNDEAD',     name:{ fr:'Prisme de pergélisol',           en:'Permafrost Prism' },        group:'weapon_staff_frost',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_FROSTSTAFF_CRYSTAL',    name:{ fr:'Bâton arctique',                 en:'Arctic Staff' },            group:'weapon_staff_frost',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'MAIN_FROSTSTAFF_AVALON',   name:{ fr:'Hurlegivre',                     en:'Chillhowl' },               group:'weapon_staff_frost',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'MAIN_FROSTSTAFF_KEEPER',   name:{ fr:'Bâton de gelée blanche',         en:'Hoarfrost Staff' },         group:'weapon_staff_frost',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },

    // ── Bâtons arcaniques ──
    { id:'MAIN_ARCANESTAFF',         name:{ fr:'Bâton ésotérique',               en:'Arcane Staff' },            group:'weapon_staff_arcane', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'2H_ARCANESTAFF',           name:{ fr:'Grand bâton ésotérique',         en:'Great Arcane Staff' },      group:'weapon_staff_arcane', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_ENIGMATICSTAFF',        name:{ fr:'Bâton énigmatique',              en:'Enigmatic Staff' },         group:'weapon_staff_arcane', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_ARCANESTAFF_HELL',      name:{ fr:'Bâton occulte',                  en:'Occult Staff' },            group:'weapon_staff_arcane', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_ENIGMATICORB_MORGANA',  name:{ fr:'Locus malveillant',              en:'Malevolent Locus' },        group:'weapon_staff_arcane', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_ARCANE_RINGPAIR_AVALON',name:{ fr:'Cercle vespérien',               en:'Evensong' },                group:'weapon_staff_arcane', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_ARCANESTAFF_CRYSTAL',   name:{ fr:'Bâton astral',                   en:'Astral Staff' },            group:'weapon_staff_arcane', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'MAIN_ARCANESTAFF_UNDEAD',  name:{ fr:'Bâton de sorcellerie',           en:'Witchwork Staff' },         group:'weapon_staff_arcane', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },

    // ── Bâtons sacrés ──
    { id:'MAIN_HOLYSTAFF',           name:{ fr:'Bâton béni',                     en:'Holy Staff' },              group:'weapon_staff_holy',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'2H_HOLYSTAFF',             name:{ fr:'Grand bâton béni',               en:'Great Holy Staff' },        group:'weapon_staff_holy',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_DIVINESTAFF',           name:{ fr:'Bâton divin',                    en:'Divine Staff' },            group:'weapon_staff_holy',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_HOLYSTAFF_HELL',        name:{ fr:'Bâton déchu',                    en:'Fallen Staff' },            group:'weapon_staff_holy',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_HOLYSTAFF_UNDEAD',      name:{ fr:'Bâton de rédemption',            en:'Redemption Staff' },        group:'weapon_staff_holy',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_HOLYSTAFF_CRYSTAL',     name:{ fr:'Bâton exalté',                   en:'Exalted Staff' },           group:'weapon_staff_holy',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'MAIN_HOLYSTAFF_AVALON',    name:{ fr:'Sanctificateur',                 en:'Hallowfall' },              group:'weapon_staff_holy',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'MAIN_HOLYSTAFF_MORGANA',   name:{ fr:'Bâton de toucher de vie',        en:'Lifetouch Staff' },         group:'weapon_staff_holy',   category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },

    // ── Bâtons de nature ──
    { id:'MAIN_NATURESTAFF',         name:{ fr:'Bâton naturel',                  en:'Nature Staff' },            group:'weapon_staff_nature', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'2H_NATURESTAFF',           name:{ fr:'Grand bâton naturel',            en:'Great Nature Staff' },      group:'weapon_staff_nature', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_WILDSTAFF',             name:{ fr:'Bâton sauvage',                  en:'Wild Staff' },              group:'weapon_staff_nature', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_NATURESTAFF_HELL',      name:{ fr:'Bâton de fléau',                 en:'Blight Staff' },            group:'weapon_staff_nature', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_NATURESTAFF_KEEPER',    name:{ fr:'Bâton effréné',                  en:'Rampant Staff' },           group:'weapon_staff_nature', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'MAIN_NATURESTAFF_KEEPER',  name:{ fr:'Bâton druidique',                en:'Druidic Staff' },           group:'weapon_staff_nature', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'MAIN_NATURESTAFF_AVALON',  name:{ fr:'Bâton souchefer',                en:'Ironroot Staff' },          group:'weapon_staff_nature', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'MAIN_NATURESTAFF_CRYSTAL', name:{ fr:'Bâton de Forgécorce',            en:'Forgebark Staff' },         group:'weapon_staff_nature', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },

    // ── Bâtons maudits ──
    { id:'MAIN_CURSEDSTAFF',         name:{ fr:'Bâton damné',                    en:'Cursed Staff' },            group:'weapon_staff_curse',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'2H_CURSEDSTAFF',           name:{ fr:'Grand bâton damné',              en:'Great Cursed Staff' },      group:'weapon_staff_curse',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_DEMONICSTAFF',          name:{ fr:'Bâton démoniaque',               en:'Demonic Staff' },           group:'weapon_staff_curse',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_SKULLORB_HELL',         name:{ fr:'Crâne damné',                    en:'Cursed Skull' },            group:'weapon_staff_curse',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_CURSEDSTAFF_MORGANA',   name:{ fr:'Bâton de la damnation',          en:'Damnation Staff' },         group:'weapon_staff_curse',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'MAIN_CURSEDSTAFF_AVALON',  name:{ fr:'Mande-ténèbres',                 en:'Shadowcaller' },            group:'weapon_staff_curse',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'MAIN_CURSEDSTAFF_UNDEAD',  name:{ fr:'Bâton de malédiction de vie',    en:'Lifecurse Staff' },         group:'weapon_staff_curse',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },
    { id:'MAIN_CURSEDSTAFF_CRYSTAL', name:{ fr:'Bâton de Putréfaction',          en:'Rotcaller Staff' },         group:'weapon_staff_curse',  category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_1h_wood' },

    // ── Bâtons métamorphes ──
    { id:'2H_SHAPESHIFTER_SET1',     name:{ fr:'Bâton rôdeur',                   en:'Prowling Staff' },          group:'weapon_shapeshifter', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_SHAPESHIFTER_SET2',     name:{ fr:'Bâton enraciné',                 en:'Rootbound Staff' },         group:'weapon_shapeshifter', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_SHAPESHIFTER_SET3',     name:{ fr:'Bâton primitif',                 en:'Primal Staff' },            group:'weapon_shapeshifter', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_SHAPESHIFTER_MORGANA',  name:{ fr:'Bâton de lune de sang',          en:'Bloodmoon Staff' },         group:'weapon_shapeshifter', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_SHAPESHIFTER_HELL',     name:{ fr:'Bâton de créature infernale',    en:'Hellspawn Staff' },         group:'weapon_shapeshifter', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_SHAPESHIFTER_KEEPER',   name:{ fr:'Bâton de terre-rune',            en:'Earthrune Staff' },         group:'weapon_shapeshifter', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_SHAPESHIFTER_AVALON',   name:{ fr:'Mande-lumière',                  en:'Lightcaller' },             group:'weapon_shapeshifter', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },
    { id:'2H_SHAPESHIFTER_CRYSTAL',  name:{ fr:'Bâton de Regard Figé',           en:'Stillgaze Staff' },         group:'weapon_shapeshifter', category:'magic_weapon',   iconGlyph:'staff',       recipeKey:'staff_2h_wood' },

    // ── Armure de tissu ──
    { id:'HEAD_CLOTH_SET1',          name:{ fr:"Capuchon d'érudit",              en:'Scholar Cowl' },            group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_SET1',         name:{ fr:"Robe d'érudit",                  en:'Scholar Robe' },            group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_SET1',         name:{ fr:"Sandales d'érudit",              en:'Scholar Sandals' },         group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },
    { id:'HEAD_CLOTH_SET2',          name:{ fr:"Capuchon d'ecclésiastique",       en:'Cleric Cowl' },             group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_SET2',         name:{ fr:"Robe d'ecclésiastique",           en:'Cleric Robe' },             group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_SET2',         name:{ fr:"Sandales d'ecclésiastique",       en:'Cleric Sandals' },          group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },
    { id:'HEAD_CLOTH_SET3',          name:{ fr:'Capuchon de mage',               en:'Mage Cowl' },               group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_SET3',         name:{ fr:'Robe de mage',                   en:'Mage Robe' },               group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_SET3',         name:{ fr:'Sandales de mage',               en:'Mage Sandals' },            group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },
    { id:'HEAD_CLOTH_MORGANA',       name:{ fr:'Capuchon de culte',              en:'Cultist Cowl' },            group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_MORGANA',      name:{ fr:'Robe de culte',                  en:'Cultist Robe' },            group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_MORGANA',      name:{ fr:'Sandales de culte',              en:'Cultist Sandals' },         group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },
    { id:'HEAD_CLOTH_KEEPER',        name:{ fr:'Capuchon de druide',             en:'Druid Cowl' },              group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_KEEPER',       name:{ fr:'Robe de druide',                 en:'Druid Robe' },              group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_KEEPER',       name:{ fr:'Sandales de druide',             en:'Druid Sandals' },           group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },
    { id:'HEAD_CLOTH_HELL',          name:{ fr:'Capuchon de monstre',            en:'Fiend Cowl' },              group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_HELL',         name:{ fr:'Robe de monstre',                en:'Fiend Robe' },              group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_HELL',         name:{ fr:'Sandales de monstre',            en:'Fiend Sandals' },           group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },
    { id:'HEAD_CLOTH_FEY',           name:{ fr:"Chapeau d'écailles féériques",   en:'Feyscale Hat' },            group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_FEY',          name:{ fr:"Robe d'écailles féériques",      en:'Feyscale Robe' },           group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_FEY',          name:{ fr:"Sandales d'écailles féériques",  en:'Feyscale Sandals' },        group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },
    { id:'HEAD_CLOTH_AVALON',        name:{ fr:'Capuchon de pureté',             en:'Cowl of Purity' },          group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_AVALON',       name:{ fr:'Robe de pureté',                 en:'Robe of Purity' },          group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_AVALON',       name:{ fr:'Sandales de pureté',             en:'Sandals of Purity' },       group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },
    { id:'HEAD_CLOTH_ROYAL',         name:{ fr:'Capuchon royal',                 en:'Royal Cowl' },              group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'hood',        recipeKey:'cloth_helm' },
    { id:'ARMOR_CLOTH_ROYAL',        name:{ fr:'Robe royale',                    en:'Royal Robe' },              group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'robe',        recipeKey:'cloth_armor' },
    { id:'SHOES_CLOTH_ROYAL',        name:{ fr:'Sandales royales',               en:'Royal Sandals' },           group:'armor_cloth',         category:'cloth_armor',     iconGlyph:'boots',       recipeKey:'cloth_boots' },

    // ══════════════════════════════════════════════════════════════
    // ÉQUIPEMENT COMMUN
    // ══════════════════════════════════════════════════════════════

    // ── Mains secondaires ──
    { id:'OFF_SHIELD',               name:{ fr:'Bouclier',                       en:'Shield' },                  group:'offhand',             category:'offhand',         iconGlyph:'shield',      recipeKey:'shield' },
    { id:'OFF_SHIELD_AVALON',        name:{ fr:'Égide astrale',                  en:'Astral Aegis' },            group:'offhand',             category:'offhand',         iconGlyph:'shield',      recipeKey:'shield' },
    { id:'OFF_SHIELD_HELL',          name:{ fr:'Bouclier de scélérat',           en:'Caitiff Shield' },          group:'offhand',             category:'offhand',         iconGlyph:'shield',      recipeKey:'shield' },
    { id:'OFF_SPIKEDSHIELD_MORGANA', name:{ fr:'Brise-face',                     en:'Facebreaker' },             group:'offhand',             category:'offhand',         iconGlyph:'shield',      recipeKey:'shield' },
    { id:'OFF_SHIELD_CRYSTAL',       name:{ fr:'Barrière Incassable',            en:'Unbreakable Ward' },        group:'offhand',             category:'offhand',         iconGlyph:'shield',      recipeKey:'shield' },
    { id:'OFF_TOWERSHIELD_UNDEAD',   name:{ fr:'Sarcophage',                     en:'Sarcophagus' },             group:'offhand',             category:'offhand',         iconGlyph:'shield',      recipeKey:'tower_shield' },
    { id:'OFF_TORCH',                name:{ fr:'Torche',                         en:'Torch' },                   group:'offhand',             category:'offhand',         iconGlyph:'staff',       recipeKey:'torch' },
    { id:'OFF_TORCH_CRYSTAL',        name:{ fr:'Torche Flammebleue',             en:'Blueflame Torch' },         group:'offhand',             category:'offhand',         iconGlyph:'staff',       recipeKey:'torch' },
    { id:'OFF_LAMP_UNDEAD',          name:{ fr:'Bougie de la crypte',            en:'Cryptcandle' },             group:'offhand',             category:'offhand',         iconGlyph:'staff',       recipeKey:'torch' },
    { id:'OFF_JESTERCANE_HELL',      name:{ fr:'Canne grimaçante',               en:'Leering Cane' },            group:'offhand',             category:'offhand',         iconGlyph:'staff',       recipeKey:'torch' },
    { id:'OFF_CENSER_AVALON',        name:{ fr:'Encens céleste',                 en:'Celestial Censer' },        group:'offhand',             category:'offhand',         iconGlyph:'staff',       recipeKey:'torch' },
    { id:'OFF_BOOK',                 name:{ fr:'Tome de sorts',                  en:'Tome of Spells' },          group:'offhand',             category:'offhand',         iconGlyph:'robe',        recipeKey:'book' },
    { id:'OFF_TOME_CRYSTAL',         name:{ fr:'Grimoire Chronostatique',        en:'Timelocked Grimoire' },     group:'offhand',             category:'offhand',         iconGlyph:'robe',        recipeKey:'book' },
    { id:'OFF_ORB_MORGANA',          name:{ fr:'Œil des secrets',                en:'Eye of Secrets' },          group:'offhand',             category:'offhand',         iconGlyph:'orb',         recipeKey:'orb' },
    { id:'OFF_TALISMAN_AVALON',      name:{ fr:'Sceptre sacré',                  en:'Sacred Scepter' },          group:'offhand',             category:'offhand',         iconGlyph:'orb',         recipeKey:'orb' },
    { id:'OFF_TOTEM_KEEPER',         name:{ fr:'Racine pivot',                   en:'Taproot' },                 group:'offhand',             category:'offhand',         iconGlyph:'totem',       recipeKey:'totem' },
    { id:'OFF_DEMONSKULL_HELL',      name:{ fr:'Miniaturisé',                    en:'Muisak' },                  group:'offhand',             category:'offhand',         iconGlyph:'totem',       recipeKey:'totem' },
    { id:'OFF_HORN_KEEPER',          name:{ fr:'Mandebrume',                     en:'Mistcaller' },              group:'offhand',             category:'offhand',         iconGlyph:'horn',        recipeKey:'horn' },

    // ── Capes ──
    { id:'CAPE',                        name:{ fr:'Cape',                        en:'Cape' },                    group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_BRIDGEWATCH',     name:{ fr:'Cape de Bridgewatch',         en:'Bridgewatch Cape' },        group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_FORTSTERLING',    name:{ fr:'Cape de Fort Sterling',       en:'Fort Sterling Cape' },      group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_LYMHURST',        name:{ fr:'Cape de Lymhurst',            en:'Lymhurst Cape' },           group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_MARTLOCK',        name:{ fr:'Cape de Martlock',            en:'Martlock Cape' },           group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_THETFORD',        name:{ fr:'Cape de Thetford',            en:'Thetford Cape' },           group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_CAERLEON',        name:{ fr:'Cape de Caerleon',            en:'Caerleon Cape' },           group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_BRECILIEN',       name:{ fr:'Cape de Brecilien',           en:'Brecilien Cape' },          group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_AVALON',             name:{ fr:'Cape avalonienne',            en:'Avalonian Cape' },          group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_SMUGGLER',           name:{ fr:'Cape de Contrebandier',       en:'Smuggler Cape' },           group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_HERETIC',            name:{ fr:'Cape des hérétiques',         en:'Heretic Cape' },            group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_UNDEAD',             name:{ fr:'Cape des morts-vivants',      en:'Undead Cape' },             group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_KEEPER',             name:{ fr:'Cape des gardiens',           en:'Keeper Cape' },             group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_MORGANA',            name:{ fr:'Cape de Morgana',             en:'Morgana Cape' },            group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_DEMON',              name:{ fr:'Cape démoniaque',             en:'Demon Cape' },              group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_BRIDGEWATCH_BP',  name:{ fr:'Armoiries de Bridgewatch',    en:'Bridgewatch Crest' },       group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_FORTSTERLING_BP', name:{ fr:'Armoiries de Fort Sterling',  en:'Fort Sterling Crest' },     group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_LYMHURST_BP',     name:{ fr:'Armoiries de Lymhurst',       en:'Lymhurst Crest' },          group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_MARTLOCK_BP',     name:{ fr:'Armoiries de Martlock',       en:'Martlock Crest' },          group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_THETFORD_BP',     name:{ fr:'Armoiries de Thetford',       en:'Thetford Crest' },          group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_CAERLEON_BP',     name:{ fr:'Armoiries de Caerleon',       en:'Caerleon Crest' },          group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_FW_BRECILIEN_BP',    name:{ fr:'Armoiries de Brecilien',      en:'Brecilien Crest' },         group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_AVALON_BP',          name:{ fr:'Armoiries avaloniennes',      en:'Avalonian Crest' },         group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_SMUGGLER_BP',        name:{ fr:'Armoiries de Contrebandier',  en:'Smuggler Crest' },          group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_HERETIC_BP',         name:{ fr:'Armoiries des hérétiques',    en:'Heretic Crest' },           group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_UNDEAD_BP',          name:{ fr:'Armoiries des morts-vivants', en:'Undead Crest' },            group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_KEEPER_BP',          name:{ fr:'Armoiries des gardiens',      en:'Keeper Crest' },            group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_MORGANA_BP',         name:{ fr:'Armoiries de Morgana',        en:'Morgana Crest' },           group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },
    { id:'CAPEITEM_DEMON_BP',           name:{ fr:'Armoiries démoniaques',       en:'Demon Crest' },             group:'cape', category:'cloth_armor', iconGlyph:'cape', recipeKey:'cape' },

    // ── Sacs ──
    { id:'BAG',        name:{ fr:'Sac',                      en:'Bag' },               group:'bag', category:'bag', iconGlyph:'bag', recipeKey:'bag' },
    { id:'BAG_INSIGHT',name:{ fr:'Sacoche de perspicacité',  en:'Satchel of Insight' },group:'bag', category:'bag', iconGlyph:'bag', recipeKey:'bag' },

    // ══════════════════════════════════════════════════════════════
    // ARTISAN & RÉCOLTE
    // ══════════════════════════════════════════════════════════════

    // ── Armure de récolteur — Fibres ──
    { id:'HEAD_GATHERER_FIBER',    name:{ fr:'Casquette de récolteur',   en:'Harvester Cap' },       group:'gatherer_armor', category:'leather', iconGlyph:'hood',   recipeKey:'leather_helm' },
    { id:'ARMOR_GATHERER_FIBER',   name:{ fr:'Tenue de récolteur',       en:'Harvester Garb' },      group:'gatherer_armor', category:'leather', iconGlyph:'jacket', recipeKey:'leather_armor' },
    { id:'SHOES_GATHERER_FIBER',   name:{ fr:'Bottes de récolteur',      en:'Harvester Workboots' }, group:'gatherer_armor', category:'leather', iconGlyph:'boots',  recipeKey:'leather_boots' },
    { id:'BACKPACK_GATHERER_FIBER',name:{ fr:'Sac à dos de récolteur',   en:'Harvester Backpack' },  group:'gatherer_armor', category:'bag',     iconGlyph:'bag',    recipeKey:'bag' },
    { id:'HEAD_GATHERER_HIDE',     name:{ fr:'Casquette de dépeceur',    en:'Skinner Cap' },         group:'gatherer_armor', category:'leather', iconGlyph:'hood',   recipeKey:'leather_helm' },
    { id:'ARMOR_GATHERER_HIDE',    name:{ fr:'Tenue de dépeceur',        en:'Skinner Garb' },        group:'gatherer_armor', category:'leather', iconGlyph:'jacket', recipeKey:'leather_armor' },
    { id:'SHOES_GATHERER_HIDE',    name:{ fr:'Bottes de dépeceur',       en:'Skinner Workboots' },   group:'gatherer_armor', category:'leather', iconGlyph:'boots',  recipeKey:'leather_boots' },
    { id:'BACKPACK_GATHERER_HIDE', name:{ fr:'Sac à dos de dépeceur',    en:'Skinner Backpack' },    group:'gatherer_armor', category:'bag',     iconGlyph:'bag',    recipeKey:'bag' },
    { id:'HEAD_GATHERER_ORE',      name:{ fr:'Casquette de mineur',      en:'Miner Cap' },           group:'gatherer_armor', category:'plate',   iconGlyph:'helm',   recipeKey:'plate_helm' },
    { id:'ARMOR_GATHERER_ORE',     name:{ fr:'Tenue de mineur',          en:'Miner Garb' },          group:'gatherer_armor', category:'plate',   iconGlyph:'plate',  recipeKey:'plate_armor' },
    { id:'SHOES_GATHERER_ORE',     name:{ fr:'Bottes de mineur',         en:'Miner Workboots' },     group:'gatherer_armor', category:'plate',   iconGlyph:'boots',  recipeKey:'plate_boots' },
    { id:'BACKPACK_GATHERER_ORE',  name:{ fr:'Sac à dos de mineur',      en:'Miner Backpack' },      group:'gatherer_armor', category:'bag',     iconGlyph:'bag',    recipeKey:'bag' },
    { id:'HEAD_GATHERER_ROCK',     name:{ fr:'Casquette de piocheur',    en:'Quarrier Cap' },        group:'gatherer_armor', category:'plate',   iconGlyph:'helm',   recipeKey:'plate_helm' },
    { id:'ARMOR_GATHERER_ROCK',    name:{ fr:'Tenue de piocheur',        en:'Quarrier Garb' },       group:'gatherer_armor', category:'plate',   iconGlyph:'plate',  recipeKey:'plate_armor' },
    { id:'SHOES_GATHERER_ROCK',    name:{ fr:'Bottes de piocheur',       en:'Quarrier Workboots' },  group:'gatherer_armor', category:'plate',   iconGlyph:'boots',  recipeKey:'plate_boots' },
    { id:'BACKPACK_GATHERER_ROCK', name:{ fr:'Sac à dos de piocheur',    en:'Quarrier Backpack' },   group:'gatherer_armor', category:'bag',     iconGlyph:'bag',    recipeKey:'bag' },
    { id:'HEAD_GATHERER_WOOD',     name:{ fr:'Casquette de bûcheron',    en:'Lumberjack Cap' },      group:'gatherer_armor', category:'leather', iconGlyph:'hood',   recipeKey:'leather_helm' },
    { id:'ARMOR_GATHERER_WOOD',    name:{ fr:'Tenue de bûcheron',        en:'Lumberjack Garb' },     group:'gatherer_armor', category:'leather', iconGlyph:'jacket', recipeKey:'leather_armor' },
    { id:'SHOES_GATHERER_WOOD',    name:{ fr:'Bottes de bûcheron',       en:'Lumberjack Workboots' },group:'gatherer_armor', category:'leather', iconGlyph:'boots',  recipeKey:'leather_boots' },
    { id:'BACKPACK_GATHERER_WOOD', name:{ fr:'Sac à dos de bûcheron',    en:'Lumberjack Backpack' }, group:'gatherer_armor', category:'bag',     iconGlyph:'bag',    recipeKey:'bag' },
    { id:'HEAD_GATHERER_FISH',     name:{ fr:'Casquette de pêcheur',     en:'Fisherman Cap' },       group:'gatherer_armor', category:'leather', iconGlyph:'hood',   recipeKey:'leather_helm' },
    { id:'ARMOR_GATHERER_FISH',    name:{ fr:'Tenue de pêcheur',         en:'Fisherman Garb' },      group:'gatherer_armor', category:'leather', iconGlyph:'jacket', recipeKey:'leather_armor' },
    { id:'SHOES_GATHERER_FISH',    name:{ fr:'Bottes de pêcheur',        en:'Fisherman Workboots' }, group:'gatherer_armor', category:'leather', iconGlyph:'boots',  recipeKey:'leather_boots' },
    { id:'BACKPACK_GATHERER_FISH', name:{ fr:'Sac à dos de pêcheur',     en:'Fisherman Backpack' },  group:'gatherer_armor', category:'bag',     iconGlyph:'bag',    recipeKey:'bag' },

    // ── Outils ──
    { id:'2H_TOOL_PICK',               name:{ fr:'Pioche',                        en:'Pickaxe' },                  group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_SICKLE',             name:{ fr:'Faucille',                      en:'Sickle' },                   group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_AXE',                name:{ fr:'Hache',                         en:'Axe' },                      group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_wood' },
    { id:'2H_TOOL_HAMMER',             name:{ fr:'Masse de pierre',               en:'Stone Hammer' },             group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_KNIFE',              name:{ fr:'Couteau à dépecer',             en:'Skinning Knife' },           group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_FISHINGROD',         name:{ fr:'Canne à pêche',                 en:'Fishing Rod' },              group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_wood' },
    { id:'2H_TOOL_SIEGEHAMMER',        name:{ fr:'Marteau de siège',              en:'Siege Hammer' },             group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_PICK_AVALON',        name:{ fr:'Pioche avalonienne',            en:'Avalonian Pickaxe' },        group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_SICKLE_AVALON',      name:{ fr:'Faucille avalonienne',          en:'Avalonian Sickle' },         group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_AXE_AVALON',         name:{ fr:'Hache avalonienne',             en:'Avalonian Axe' },            group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_wood' },
    { id:'2H_TOOL_HAMMER_AVALON',      name:{ fr:'Masse de pierre avalonienne',   en:'Avalonian Stone Hammer' },   group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_KNIFE_AVALON',       name:{ fr:'Couteau à dépecer avalonien',   en:'Avalonian Skinning Knife' }, group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },
    { id:'2H_TOOL_SIEGEHAMMER_AVALON', name:{ fr:'Marteau de siège avalonien',    en:'Avalonian Siege Hammer' },   group:'tool', category:'tool', iconGlyph:'tool', recipeKey:'tool_metal' },

    // ══════════════════════════════════════════════════════════════
    // CONSOMMABLES
    // ══════════════════════════════════════════════════════════════

    { id:'POTION_HEAL',   name:{ fr:'Potion de soin',   en:'Healing Potion' },
      tierNames:{ fr:{2:'Potion de soin mineure',4:'Potion de soin',6:'Potion de soin majeure'}, en:{2:'Minor Healing Potion',4:'Healing Potion',6:'Major Healing Potion'} },
      group:'potion', category:'consumable', iconGlyph:'potion', recipeKey:'potion' },
    { id:'POTION_ENERGY', name:{ fr:"Potion d'énergie", en:'Energy Potion' },
      tierNames:{ fr:{2:"Potion d'énergie mineure",4:"Potion d'énergie",6:"Potion d'énergie majeure"}, en:{2:'Minor Energy Potion',4:'Energy Potion',6:'Major Energy Potion'} },
      group:'potion', category:'consumable', iconGlyph:'potion', recipeKey:'potion' },
    { id:'BREAD',      name:{ fr:'Pain',    en:'Bread' },
      tierNames:{ fr:{4:'Pain'}, en:{4:'Bread'} },
      group:'food', category:'consumable', iconGlyph:'food', recipeKey:'food_simple' },
    { id:'MEAL_SOUP',  name:{ fr:'Soupe',   en:'Soup' },
      tierNames:{ fr:{3:'Soupe de blé',5:'Soupe aux choux'}, en:{3:'Wheat Soup',5:'Cabbage Soup'} },
      group:'food', category:'consumable', iconGlyph:'food', recipeKey:'food_simple' },
    { id:'MEAL_SALAD', name:{ fr:'Salade',  en:'Salad' },
      tierNames:{ fr:{2:'Salade de haricots',4:'Salade de navets',6:'Salade de patates'}, en:{2:'Bean Salad',4:'Turnip Salad',6:'Potato Salad'} },
      group:'food', category:'consumable', iconGlyph:'food', recipeKey:'food_simple' },
    { id:'MEAL_STEW',  name:{ fr:'Ragoût',  en:'Stew' },
      tierNames:{ fr:{4:'Ragoût de chèvre',6:'Ragoût de mouton',8:'Ragoût de bœuf'}, en:{4:'Goat Stew',6:'Mutton Stew',8:'Beef Stew'} },
      group:'food', category:'consumable', iconGlyph:'food', recipeKey:'food_complex' },
  ],
};
